name: vivera
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.6.0
  firebase_messaging: ^15.2.7
  go_router: ^15.2.3
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  provider: ^6.1.5
  intl: ^0.20.2
  flutter_localization: ^0.3.3
  flutter_svg: ^2.2.0
  equatable: ^2.0.7
  connectivity_plus: ^6.1.4
  url_launcher: ^6.3.1
  share_plus: ^11.0.0
  dartz: ^0.10.1
  cached_network_image: ^3.4.1
  fluttertoast: ^8.2.12
  http: ^1.4.0
  get_it: ^8.0.3
  shared_preferences: ^2.5.3
  skeleton_text: ^3.0.1
  lottie: ^3.3.1
  fittor: ^1.1.3+1
  pinput: ^5.0.1
  permission_handler: ^12.0.0+1
  video_player: ^2.10.0
  youtube_player_iframe: ^5.2.1
  chewie: ^1.11.3
  carousel_slider: ^5.1.1
  marquee: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/animation/
    - assets/data/
    - assets/images/
    - assets/videos/
